CREATE DATABASE User;
USE User;
CREATE TABLE members(
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255)  NOT NULL,
    password VARCHAR(255) NOT NULL,
    mail VARCHAR(255) UNIQUE NOT NULL
);